customhost = "scripting651.cpk67mivo0rf.us-east-1.rds.amazonaws.com"
customuser = "mysql_admin"
custompass = "1nsecure"
customdb = "employee"
custombucket = "addemployee651"
customregion = "us-east-1"
